# Generated by Django 3.1.3 on 2021-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superstar',
            field=models.BooleanField(default=False),
        ),
    ]
